#!/usr/bin/env bash

set -e

docker build . -t "gjtorikian/bin-tailscale:main" -f "bin/tailscale/Dockerfile" "$@"
docker build . -t "gjtorikian/bin-op:main" -f "bin/op/Dockerfile" "$@"

docker build . -t "gjtorikian/base-rails:main" -f "base/rails/Dockerfile" "$@"

docker build . -t "gjtorikian/app-plug:main" -f "app/plug/ruby/Dockerfile" "$@"
